#!/usr/bin/env python3
"""Generate deployment/compose.yml from the latest release across backend + web repos."""

from __future__ import annotations

import argparse
import importlib.util
import shutil
import sys
import tempfile
import urllib.error
import urllib.request
from pathlib import Path

import yaml

SCRIPTS_DIR = Path(__file__).resolve().parent
DEPLOYMENT_ROOT = SCRIPTS_DIR.parent
sys.path.insert(0, str(SCRIPTS_DIR))

from git_remote import (  # noqa: E402
    fetch_raw_file,
    fetch_semver_tags,
    resolve_git_token,
    semver_key,
)

_gen_spec = importlib.util.spec_from_file_location(
    "generate_compose",
    SCRIPTS_DIR / "generate-compose.py",
)
if _gen_spec is None or _gen_spec.loader is None:
    raise RuntimeError("Could not load generate-compose.py")
_generate_compose = importlib.util.module_from_spec(_gen_spec)
_gen_spec.loader.exec_module(_generate_compose)
generate = _generate_compose.generate
dump_yaml_str = _generate_compose.dump_yaml_str

DEFAULT_BACKEND_REPO = "https://github.com/fromchat-messenger/backend.git"
DEFAULT_WEB_REPO = "https://github.com/fromchat-messenger/web.git"
DEFAULT_COMPONENTS = ("backend", "frontend", "caddy")

FULL_STACK_PACKAGES = (
    "backend",
    "messaging",
    "file_storage",
    "postgres",
    "web",
    "caddy",
    "livekit",
    "haproxy",
)

GENERATED_HEADER = (
    "# Auto-generated by deployment/scripts/sync-published-compose.py — do not edit manually.\n"
    "# One-click: docker compose --env-file .env up -d\n"
    "# Tag: {tag}\n"
)


def dockerhub_tag_exists(service: str, tag: str) -> bool:
    url = f"https://hub.docker.com/v2/repositories/fromchat/{service}/tags/{tag}/"
    req = urllib.request.Request(url, headers={"User-Agent": "fromchat-sync-compose"})
    try:
        with urllib.request.urlopen(req, timeout=45) as resp:
            return resp.status == 200
    except urllib.error.HTTPError as exc:
        return exc.code == 200
    except (urllib.error.URLError, TimeoutError):
        return False


def packages_ready(tag: str) -> bool:
    return all(dockerhub_tag_exists(service, tag) for service in FULL_STACK_PACKAGES)


def resolve_latest_published_tag(
    backend_repo: str,
    web_repo: str,
    token: str | None,
) -> str | None:
    backend_tags = fetch_semver_tags(backend_repo, token)
    web_tags = fetch_semver_tags(web_repo, token)
    common = backend_tags & web_tags
    if not common:
        return None
    for tag in sorted(common, key=semver_key, reverse=True):
        if packages_ready(tag):
            return tag
    return None


def apply_restart_always(compose_path: Path) -> None:
    """Force restart: always on every service (this script only)."""
    doc = yaml.safe_load(compose_path.read_text(encoding="utf-8")) or {}
    services = doc.get("services")
    if not isinstance(services, dict):
        return
    for cfg in services.values():
        if isinstance(cfg, dict):
            cfg["restart"] = "always"
    compose_path.write_text(dump_yaml_str(doc), encoding="utf-8")


def sync_published_compose(
    *,
    output: Path,
    backend_repo: str,
    web_repo: str,
    token: str | None,
    components: tuple[str, ...] = DEFAULT_COMPONENTS,
) -> str | None:
    tag = resolve_latest_published_tag(backend_repo, web_repo, token)
    if not tag:
        print(
            "No semver tag with all required fromchat/* images on Docker Hub.",
            file=sys.stderr,
        )
        return None

    print(f"Latest publishable tag: {tag}", file=sys.stderr)

    tmp = Path(tempfile.mkdtemp(prefix="fromchat-sync-compose-"))
    try:
        backend_compose = tmp / "backend.compose.yml"
        web_compose = tmp / "frontend.compose.yml"
        backend_compose.write_bytes(
            fetch_raw_file(backend_repo, tag, "compose.yml", token)
        )
        web_compose.write_bytes(
            fetch_raw_file(web_repo, tag, "compose.yml", token)
        )

        generate(
            backend_compose=backend_compose,
            frontend_compose=web_compose,
            tag=tag,
            components=set(components),
            output=output,
            include_updater=False,
        )
        apply_restart_always(output)

        body = output.read_text(encoding="utf-8")
        while body.startswith("#"):
            nl = body.find("\n")
            if nl < 0:
                break
            body = body[nl + 1 :]
        body = body.lstrip("\n")
        output.write_text(GENERATED_HEADER.format(tag=tag) + body, encoding="utf-8")
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    print(f"Wrote {output}", file=sys.stderr)
    return tag


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Resolve the latest common release tag and write a single production "
            "compose.yml with fromchat/* images (no updater)."
        )
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEPLOYMENT_ROOT / "compose.yml",
        help="Output compose.yml path (default: deployment/compose.yml)",
    )
    parser.add_argument("--backend-repo", default=DEFAULT_BACKEND_REPO)
    parser.add_argument("--web-repo", default=DEFAULT_WEB_REPO)
    parser.add_argument(
        "--components",
        default=",".join(DEFAULT_COMPONENTS),
        help="Comma-separated components (default: backend,frontend,caddy)",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    token = resolve_git_token()
    components = tuple(
        c.strip().lower()
        for c in args.components.split(",")
        if c.strip() and c.strip().lower() != "updater"
    )
    if not components:
        components = DEFAULT_COMPONENTS

    tag = sync_published_compose(
        output=args.output.resolve(),
        backend_repo=args.backend_repo,
        web_repo=args.web_repo,
        token=token,
        components=components,
    )
    if not tag:
        raise SystemExit(0)
    print(tag)


if __name__ == "__main__":
    main()
